### ISSUE TITLE
ERP_Ld3 test fails COMPARE_base_rest

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#638]
### What happened?

This restart test fails
ERP_Ld3_Vmct.f19_f19_mg17.QPC4.cheyenne_intel.cam-outfrq3d

This fails in tags cam6_3_071 and cam6_3_007.  However, it passes in cam6_3_006.  So the changes that went into cam6_3_007 seem to be the culprit which are "Weak scaling infrastructure and bug fixes" (by @gold2718).

### What are the steps to reproduce the bug?

qcmd -- create_test --walltime 00:15:00 --test-id myid ERP_Ld3_Vnuopc.f19_f19_mg17.QPC4.cheyenne_intel.cam-outfrq3d

### What CAM tag were you using?

cam6_3_007 - cam6_3_071

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/scratch/fvitt/ERP_Ld3_Vmct.f19_f19_mg17.QPC4.cheyenne_intel.cam-outfrq3d.cam6_3_007

### Will you be addressing this bug yourself?

No

**Comment by gold2718** [comment]
The failure in cam6_3_007 was fixed in cam6_4_008 so I'm not sure how that is relevant now. Please explain.

**Comment by fvitt** [comment]
> The failure in cam6_3_007 was fixed in cam6_4_008 so I'm not sure how that is relevant now. Please explain.

@gold2718 
As stated in the description, this test also false in the latest cam tag.

**Comment by gold2718** [comment]
Yes, however, why do you think it is related to the failure in cam6_3_007 which was fixed?

**Comment by fvitt** [comment]
I have not found a tag later than cam6_3_006 where this test passes.  It fails in cam6_3_007, cam6_3_008, cam6_3_010, and cam6_3_071.  The latest tag I found where this passes is cam6_3_006.

**Comment by gold2718** [comment]
The change in cam6_3_007 that causes this failure is an addition of a reprosum error check in cam/outfrq3d.
The test passes without that check (i.e., with default global sum values).
I'm tempted to close this as a won't fix. Any objections?

**Comment by fvitt** [comment]
@gold2718 
Are these the line you removed from user_nl_cpl
 reprosum_diffmax=1.0e-14
 reprosum_recompute=.true.
??

I removed these and the test still fails for me....

**Comment by gold2718** [comment]
Are you sure you reran the test? I commented them out in outfrq3d/user_nl_cpl and the test passed. 
I think to try it with a rerun, you have to take it out of both case directories. Did you try that?

**Comment by fvitt** [comment]
Well OK.   The case2 copy of user_nl_cpl was hiding from me... So removing those reprosum settings from outfrq3d/user_nl_cpl does indeed solve the problem.  Shouldn't we fix this in the head of cam_development before we close this issue, even though the fix is simple?

**Comment by gold2718** [comment]
What exactly is broken that needs fixing? We added that check to certain compsets where it should pass. The test reported in this issue is not one of them. I think the solution is to not use those user mods for this compset. What do you suggest?

**Comment by fvitt** [comment]
It was reported by Chris Fischer that the following test failed in the beta09 tests and it has not passed since beta01:
ERP_Ld3_Vnuopc.f19_f19_mg17.FWsc2010climo.cheyenne_intel.cam-outfrq3d

Don't you think we should try to fix it?  Removing the reprosum settings from outfrq3d/user_nl_cpl solves the problem.

I don't understand what those settings do and why they needed to be added to the tests.    I would not imagine the normal user would ever use the settings.

**Comment by gold2718** [comment]
Oh, now I get it, thanks.
I think the solution is to create a new testmod, say `outfrq3d_norepro`, that does not use the reprosum test.
Or convert the working tests to `outfrq3d_repro`.
Of course, one could wonder why `FWsc2010climo` does not pass with reprosum but I'd bet it is something in the way the SC code works and I vote to not worry about that.

**Comment by fvitt** [comment]
> Of course, one could wonder why `FWsc2010climo` does not pass with reprosum but I'd bet it is something in the way the SC code works and I vote to not worry about that.

All of the compsets I tried (QPC4, F2010climo and FWsc2010climo) with the ERP_L3d + outfrq3d (with the reprosum settings) test failed.  So I don't believe it is something specific with the way WACCM-SC works.  It seems that those reprosum settings are not giving reproducible results on the longer run times (3 days).  Like I mentioned earlier, I don't know what those settings do and don't know what to expect for longer test runs.

**Comment by gold2718** [comment]
Took another look and no aux_cam test is using outfrq3d so I agree with just taking out those two lines in user_nl_cpl
Sorry for being so slow on the uptake (having a bad week).

**Comment by gold2718** [comment]
@cacraigucar, any reason this fix could not go into https://github.com/ESCOMP/CAM/pull/636?
